### ISSUE TITLE
No static method rememberModalBottomSheetState

### ISSUE THREAD

**Issue by joraavetisyan** [ahmmedrejowan/CountryCodePickerCompose#1]
I have multymodule architecture and I'm getting such error, can you help to solve?

AndroidRuntime          com.skishift.ptop                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.skishift.ptop, PID: 11298
                                                                                                    java.lang.NoSuchMethodError: No static method rememberModalBottomSheetState(ZLkotlin/jvm/functions/Function1;Landroidx/compose/runtime/Composer;II)Landroidx/compose/material3/SheetState; in class Landroidx/compose/material3/ModalBottomSheet_androidKt; or its super classes (declaration of 'androidx.compose.material3.ModalBottomSheet_androidKt' appears in /data/data/com.skishift.ptop/code_cache/.overlay/base.apk/classes.dex)
                                                                                                    	at com.rejowan.ccpc.CountryPickerBottomSheetKt.CountryPickerBottomSheet-88mDfTA(CountryPickerBottomSheet.kt:45)
                                                                                                    	at com.rejowan.ccpc.CountryCodePickerKt.CountryCodePicker-ueL0Wzs(CountryCodePicker.kt:62)
                                                                                                    	at com.rejowan.ccpc.CountryCodePickerKt$CountryCodePicker$3.invoke(Unknown Source:33)
                                                                                                    	at com.rejowan.ccpc.CountryCodePickerKt$CountryCodePicker$3.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1069)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@6a94c2a, androidx.compose.ui.platform.MotionDurationScaleImpl@dc66a1b, StandaloneCoroutine{Cancelling}@db197b8, AndroidUiDispatcher@127d991]

**Comment by ahmmedrejowan** [comment]
Can you share your implementations?

**Comment by glots-a** [comment]
I have updated materialUi and also got this error!
